#!/usr/bin/env node
/**
 * OpenClaw GitHub Chat Export Module
 * 
 * Token must be set in environment variable: GITHUB_TOKEN
 * 
 * Usage:
 *   export GITHUB_TOKEN="ghp_xxx"
 *   node export-chat.js "Title" "Markdown Content"
 * 
 * Output:
 *   GitHub URL to the rendered file
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Get token from environment (not stored in files)
const TOKEN = process.env.GITHUB_TOKEN;

// Configuration
const CONFIG = {
    repo: 'yaoshining/openclaw-chat-archives',
    branch: 'main',
    messagesDir: 'messages',
    workspace: '/home/node/.openclaw/workspace/chat-archives',
    baseUrl: 'https://github.com/yaoshining/openclaw-chat-archives/blob/main/messages/'
};

// Get arguments
const title = process.argv[2] || 'Chat Export';
const content = process.argv[3] || '';

// Read stdin if no content provided
if (!content && !process.stdin.isTTY) {
    let stdin = '';
    process.stdin.on('data', chunk => stdin += chunk);
    process.stdin.on('end', () => exportChat(title, stdin));
} else {
    exportChat(title, content);
}

function exportChat(title, content) {
    if (!content.trim()) {
        console.log('No content to export');
        process.exit(1);
    }

    // Generate filename
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = `${CONFIG.messagesDir}/${timestamp}.md`;
    const filepath = path.join(CONFIG.workspace, filename);

    // Create markdown file
    const markdown = generateMarkdown(title, content);
    fs.writeFileSync(filepath, markdown);

    // Git operations
    try {
        execSync('git add .', { cwd: CONFIG.workspace, stdio: 'inherit' });
        execSync(`git commit -m "Auto-export: ${title.slice(0, 50)}"`, { 
            cwd: CONFIG.workspace, 
            stdio: 'inherit' 
        });
        
        // Push using token from environment
        if (TOKEN) {
            const remoteUrl = `https://${TOKEN}@github.com/${CONFIG.repo}.git`;
            execSync(`git push "${remoteUrl}" ${CONFIG.branch}`, { 
                cwd: CONFIG.workspace, 
                stdio: 'inherit' 
            });
        } else {
            execSync(`git push origin ${CONFIG.branch}`, { 
                cwd: CONFIG.workspace, 
                stdio: 'inherit' 
            });
        }
    } catch (e) {
        console.error('Git operation failed:', e.message);
        // Still output URL even if push failed
    }

    // Output URL
    const url = CONFIG.baseUrl + path.basename(filename);
    console.log(url);
}

function generateMarkdown(title, content) {
    return `# ${title}

**Exported**: ${new Date().toISOString().slice(0, 10)} ${new Date().toISOString().slice(11, 19)} UTC

---

${content}

---

*Auto-generated by OpenClaw Chat Export*
`;
}
