#!/usr/bin/env node
/**
 * OpenClaw GitHub Chat Export Module
 * 
 * 使用方式:
 *   1. 从参数: node export-chat.js "标题" "内容"
 *   2. 从 stdin: echo "内容" | node export-chat.js "标题"
 *   3. 从文件: node export-chat.js "标题" < file.md
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

// 获取 token（环境变量）
const TOKEN = process.env.GITHUB_TOKEN;

// 配置
const CONFIG = {
    repo: 'yaoshining/openclaw-chat-archives',
    branch: 'main',
    messagesDir: 'messages',
    workspace: '/home/node/.openclaw/workspace/chat-archives',
    baseUrl: 'https://github.com/yaoshining/openclaw-chat-archives/blob/main/messages/'
};

// 主函数
async function main() {
    // 获取标题（第一个参数）
    const title = process.argv[2] || 'Chat Export';
    
    // 检查是否有 stdin 内容
    if (!process.stdin.isTTY) {
        // 从 stdin 读取
        const rl = readline.createInterface({
            input: process.stdin,
            terminal: false
        });
        
        let content = '';
        for await (const line of rl) {
            content += line + '\n';
        }
        
        await exportChat(title, content.trim());
    } else if (process.argv[3]) {
        // 从参数读取
        await exportChat(title, process.argv[3]);
    } else {
        console.log('Usage:');
        console.log('  node export-chat.js "Title" "Content"');
        console.log('  echo "Content" | node export-chat.js "Title"');
        console.log('  node export-chat.js "Title" < file.md');
        process.exit(1);
    }
}

async function exportChat(title, content) {
    if (!content || !content.trim()) {
        console.log('Error: No content provided');
        process.exit(1);
    }

    // 生成文件名
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = `${CONFIG.messagesDir}/${timestamp}.md`;
    const filepath = path.join(CONFIG.workspace, filename);

    // 创建 markdown 文件
    const markdown = generateMarkdown(title, content);
    fs.writeFileSync(filepath, markdown);

    // Git 操作
    try {
        execSync('git add .', { cwd: CONFIG.workspace, stdio: 'inherit' });
        execSync(`git commit -m "Auto-export: ${title.slice(0, 50).replace(/"/g, '\\"')}"`, { 
            cwd: CONFIG.workspace, 
            stdio: 'inherit' 
        });
        
        // 推送
        if (TOKEN) {
            const remoteUrl = `https://${TOKEN}@github.com/${CONFIG.repo}.git`;
            execSync(`git push "${remoteUrl}" ${CONFIG.branch}`, { 
                cwd: CONFIG.workspace, 
                stdio: 'inherit' 
            });
        } else {
            execSync(`git push origin ${CONFIG.branch}`, { 
                cwd: CONFIG.workspace, 
                stdio: 'inherit' 
            });
        }
    } catch (e) {
        console.error('Git operation warning:', e.message);
    }

    // 输出 URL
    const url = CONFIG.baseUrl + path.basename(filename);
    console.log(url);
}

function generateMarkdown(title, content) {
    return `# ${title}

**Exported**: ${new Date().toISOString().slice(0, 10)} ${new Date().toISOString().slice(11, 19)} UTC

---

${content}

---

*Auto-generated by OpenClaw Chat Export*
`;
}

main().catch(console.error);
