# OpenClaw Chat Export Configuration
# Token is stored in environment variable GITHUB_TOKEN
# Set it before running: export GITHUB_TOKEN="ghp_xxx"

REPO="yaoshining/openclaw-chat-archives"
BRANCH="main"
MESSAGES_DIR="messages"
WORKSPACE="/home/node/.openclaw/workspace/chat-archives"

# Get token from environment (not stored in files)
TOKEN="${GITHUB_TOKEN}"

# Generate filename with timestamp
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
FILENAME="${MESSAGES_DIR}/${TIMESTAMP}.md"

# Create messages directory if not exists
mkdir -p "${WORKSPACE}/${MESSAGES_DIR}"

# Function to export chat
export_chat() {
    local title="$1"
    local content="$2"
    
    # Create markdown file
    cat > "${WORKSPACE}/${FILENAME}" << EOF
# $title

**Exported**: $(date '+%Y-%m-%d %H:%M UTC')

---

$content

---

*Auto-generated by OpenClaw Chat Export*
EOF
    
    # Git operations
    cd "${WORKSPACE}"
    git add "${FILENAME}"
    git commit -m "Auto-export: ${title}" 2>/dev/null
    
    # Push with token in URL (not stored)
    if [ -n "$TOKEN" ]; then
        git push "https://${TOKEN}@github.com/${REPO}.git" "${BRANCH}" 2>/dev/null || \
        git push origin "${BRANCH}" 2>/dev/null
    else
        git push origin "${BRANCH}" 2>/dev/null
    fi
    
    # Return GitHub URL
    echo "https://github.com/${REPO}/blob/${BRANCH}/${FILENAME}"
}

# Run export
export_chat "$1" "$2"
